"""Migracion inicial

Revision ID: 06036282e698
Revises: 
Create Date: 2025-11-02 12:27:51.485579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06036282e698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
