"""Longitud de 15 a campo genre 

Revision ID: 47f17120b053
Revises: 06036282e698
Create Date: 2025-11-02 12:52:04.810359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f17120b053'
down_revision = '06036282e698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###
